theme = "catppuccin_mocha"

[editor]
auto-pairs = false
bufferline = "always"
color-modes = true
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

#"C-." = "code_action"

"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"

"A-h" = "goto_previous_buffer"
"A-l" = "goto_next_buffer"

"A-/" = "toggle_comments"

"space" = { c = ":buffer-close", C = ":buffer-close-others" }

"C-." = "completion"

[keys.select]
"C-." = "completion"

[keys.insert]
"C-j" = "code_action"
"C-space" = "completion"
