
[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }
auto-format = true


[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"] }
auto-format = true


[[language]]
name = "rust"
indent = { tab-width = 2, unit = "  " }
auto-format = true


[[language]]
name = "toml"
indent = { tab-width = 2, unit = "  " }
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true


[[language]]
name = "typescript"
language-servers = [
  { except-features = [
    "format",
  ], name = "typescript-language-server" },
  "eslint",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  { except-features = [
    "format",
  ], name = "typescript-language-server" },
  "eslint",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [
  { except-features = [
    "format",
  ], name = "typescript-language-server" },
  "eslint",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  { except-features = [
    "format",
  ], name = "typescript-language-server" },
  "eslint",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"
timeout = 60

[language-server.eslint.config]
format = false
nodePath = ""
onIgnoredFiles = "off"
quiet = false
rulesCustomizations = []
useESLintClass = false
run = "onType"
validate = "on"
experimental = { useFlatConfig = false }
workingDirectory = { mode = "location" }


[language-server.eslint.config.codeAction]
[language-server.eslint.config.codeAction.disableRuleComment]
enable = true
location = "separateLine"

[language-server.eslint.config.codeAction.showDocumentation]
enable = true

[language-server.eslint.config.codeActionOnSave]
enable = true
mode = "all"

[language-server.typescript-language-server]
args = ["--stdio"]
command = "typescript-language-server"
timeout = 60

[language-server.typescript-language-server.config]
documentFormatting = false
